# Acknowledgments {-}

\pagenumbering{roman}
\setcounter{page}{9}

Writing this dissertation has been a demanding yet fulfilling journey, intertwined with various professional and personal experiences. I therefore want to express my immense gratitude to my supervisors, peers, institutions, and loved ones for their support and encouragement, which played a crucial role in the completion of my dissertation.

The unwavering support and mentoring of Annalisa Pelizza has been invaluable in guiding me through the complexities of this dissertation. Thank you for your encouragement and guidance, which helped propel me and the research in the right direction. Your close engagement with the work, along with your always insightful feedback, has had a profound impact on both the quality of the research and my growth as a scholar and writer. I am grateful to Stefan Kuhlmann for his insightful oversight and holistic perspective on my project. Your seasoned guidance, drawing from years of supervising other students, combined with a knowledge of relevant academic fields, has provided fresh perspectives and helped keep the project on track. I am grateful to Maurice van Keulen for his positive energy and sustained interest in the project as it expanded into other academic fields. It was valuable to have an extra set of eyes to double-check the technical details in the research and provide fresh perspectives on presenting findings visually. Thank you as well to the members of the graduation committee for their involvement and engagement with my work during these final stages of the process. While having a team of three supervisors with different backgrounds and perspectives presented some complexities, I am confident that the committee members and readers acknowledge the positive impact of their diverse engagements on the dissertation.

The research would not have been possible without the funding from the European Research Council (ERC) which funded the Processing Citizenship project under the European Union’s Horizon 2020 research and innovation program (grant agreement No 714463). Annalisa Pelizza deserves thanks for leading the development of this project and bringing together an exceptional team of researchers. I want to give a special shout-out to Chiara Loschi, Lorenzo Olivieri, Paul Trauttmansdorff, and Claudio Coletta for their incredible collaboration and the countless enjoyable moments in and outside of the office, and thought-provoking discussions about the project and much more. Additionally, I want to acknowledge the valuable contributions from other project members at different times, including Andrea Pettrachin, Yoren Lausberg, Chiara Andreoli, Annalisa Bacchi, Stephan Scheel, Ermioni Frezouli.

I extend my heartfelt thanks to the WCC Group for their collaboration and assistance in facilitating my research project. I wish to express my heartfelt thanks to Roelof Troost for his exceptional support and confidence in my research on the ELISE data matching system. I want to express my gratitude to the identity and security team members, along with other individuals at WCC, for generously sharing their insights and expertise in this particular field with me. In addition, I would like to offer my heartfelt thanks to the employees of the Netherlands’ Immigration and Naturalization Service (IND) for their kind cooperation in generously sharing their valuable work experiences.

I want to thanks UTwente STePS/KiTeS colleagues for their support, insightful reflections, and encouragement during our coffee breaks, lunchtime discussions, and presentations: Ewert Aukes, Binod Koirala, Mario Pinzon-Camargo, Arie Rip, Klaasjan Visscher, Peter Stegmaier, Adri Albert de la Bruhèze, Kornelia Konrad, Lissa Roberts. I also want to thank my fellow researchers at the Department of Philosophy and Communication Studies during my stay at the University of Bologna, who offered a pleasant respite in our shared room at the department, which was an especially welcome change after working remotely during the COVID-19 pandemic. I appreciated the moments to take breaks from work, whether it was during lunch, an apperitivo, or _prendere un caffè_: Antonella, Chiara, Eduardo, Filomena, Gioacchino, John, Monica, Matteo, Nicola.

I want to thank Elize Schiweck and Tatiana Mattioli for their help and attentiveness in handling administrative duties and personal support at the University of Twente and University of Bologna respectively. More broadly, I also want to extend my heartfelt thanks to all those involved in the work that forms the backbone of our academic pursuits. This includes the dedicated administrative staff and all the support personnel whose behind-the-scenes efforts ensure the smooth functioning of our academic community.

When it came to facilities, I had a wonderful time exploring the high-tech and green campus of the University of Twente. The experience of living and working on a campus that offers excellent facilities, along with the opportunity to take daily walks in the forest and explore the unexpected beauty of Overijssel through cycling and camping, was a true blessing, especially during the difficult times of the Covid pandemic. Equally inspiring was the time spent in the historic city and university of Bologna, with its gorgeous red buildings, porticoes, and beautiful surrounding hills. My heartfelt thanks to everyone at the University of Bologna and the University of Twente who made it possible for me to spend time at these institutions.

I am happy about the opportunities that the Processing Citizenship program and I had to contribute to larger academic networks. Through these collaborations, we were able to ignite new ideas and establish connections that made our work more meaningful and enjoyable. I feel privileged to have played a role in the STS-MIGTEC network, which has emerged as a significant network for scholars investigating the connection between STS and critical migration, security, and border studies. I want to acknowledge and thank Nina Amelung, Silvan Pollozek, Olga Usachova, Andrea Berger, Aristotle Tympas, Vasilis Argyriou, and all the others who have gone above and beyond to make this network possible. I would also like to express my sincere gratitude to Georgios Glouftsios, Rocco Bellanova, Matthias Leese, Fran Meissner, Nina Dewi Toft Djanegara, Ana Valdivia, and many others who have been involved in this and other academic networks, for their valuable collaborations, contributions, and insightful discussions regarding my work.

Bologna proved to be an excellent environment for us to grow and expand our networks. Here, I am also thankful for having had the privilege of being a part of the organizing committee for the 2023 conference of the Italian Association for Social Studies of Science and Technology in Bologna. Juggling my PhD completion and organizing this event was tough, but the conference turned out to be truly amazing. I wish to extend my heartfelt thanks to Paolo Giardullo, Barbara Saracino, Agnese Cretella, and Simone Arnaldi.

Starting my PhD journey with a software development background, I had to adjust to a very different academic field. However, the WTMC graduate school program provided me with an exceptional education in Science and Technology Studies, and I feel blessed to have been a part of it. I would like to extend my heartfelt appreciation to the exceptional WTMC training coordinators for their immense effort in planning the amazing workshops and schools: Anne Beaulieu, Bernike Pasveer, Andreas Weber. I am thankful to my fellow WTMCers for making Soeterbeeck a place of curiosity and creativity, where we had amazing moments of connection.

My heartfelt appreciation goes out to my friends, both near and far, for their support and understanding throughout this lengthy dissertation journey. Despite the challenges and geographical distances, I hold dear the moments we’ve shared in Bologna, Brussels, Enschede, Maynal, and, of course, even online during the pandemic. This thanks extends to the awesome communities who have made life more enjoyable over the years: the Enschede Swing Out Loud swing dancers, the Haraway book club crew, my fellow Korean language learners in Bologna at the Centro Studi d'Arte Estremo-Orientale, P-NUT members for the , and so many others. Special appreciation goes to Gaetan, Ludovic, Isabel, Iza, Lloyd, Mathijs, Elisa, Kaat, Bart, Kristina, Carla, Fenna, Jef, Iris, Ming, Menno, and countless others.

Graag wil ik ook mijn familie bedanken. Papa, bedankt voor je steun tijdens dit hele proces en voor altijd een thuisbasis te bieden waar we naar terug kunnen keren. Jeroen en Kelly, hartelijk dank; het is altijd leuk om samen tijd door te brengen, bordspelletjes te spelen, en het is geweldig om te zien hoe jullie twee ketjes, Yoshi en Yuna, zijn opgegroeid gedurende mijn hele proefschrift. Ook bedankt aan Michel, Linda, Rudi, Merce, &co voor de gezellige momenten samen. Het doet me veel verdriet dat mijn mama er niet meer is om dit moment mee te maken, maar je hebt me enorm gesteund en ik weet zeker dat je enorm trots zou zijn geweest op mij.

Ontelbare dank aan mijn wederhelft Sujin. Bedankt voor je steun tijdens moeilijke periodes en voor je voortdurende geloof in mij en mijn werk. Ons verhaal is onlosmakelijk verwoven met dit proefschrift, en ik koester alle momenten en plekken die we in deze tijd samen hebben mogen beleven en ontdekken. Ik kijk uit naar de vele mooie momenten die ons nog te wachten staan. 우리 \space 한국 \space 가족들에게 \space 감사합니다. 응원해주시고 \space 함께 \space 나누는 \space 모든 \space 순간에 \space 감사합니다.
