# Summary {.unnumbered .unlisted}

\addcontentsline{toc}{part}{Summary}

\thispagestyle{plain}

\chaptermark{Summary}

This dissertation analyzes the interconnections between data matching technologies, identification practices, and transnational commercialized security infrastructures, particularly in relation to migration management and border control. The research was motivated by a curiosity about the intersection between identity data matching and the challenges authorities encounter when identifying individuals, especially the “blind spots” caused by incomplete data, aliases, and uncertainties. The dissertation addresses the following main research question: “How are practices and technologies for matching identity data in migration management and border control shaping and shaped by transnational commercialized security infrastructures?”

The dissertation begins by presenting an overview of the literature regarding the connections between data matching technology, which is used across various sectors, and its interrelationships with the internationalization, commercialization, securitization, and infrastructuring of identification infrastructure. This overview highlights a noticeable gap in the understanding of how data matching influences the meaning of the interconnected data and shapes relationships between organizations that use it. To address this gap, Chapter 3 proposes a methodological framework for using data matching as both a research topic and a resource for answering specific sub-questions related to specific aspects of data matching.

Chapter 4 emphasizes the significance of data models in information systems for categorizing individuals and establishing connections between different data models for accurate matching. The analysis of this aspect of data matching is made possible by introducing the “Ontology Explorer”, which serves as a novel method for examining the knowledge and assumptions embedded within data models. By applying this method to analyze national and transnational data infrastructures for population management, this method is shown to reveal authorities’ imaginaries on people-on-the-move. In this way, the method demonstrates the importance of data categories in data models, as they are crucial for data matching while also offering valuable insights into how authorities enact people in different ways.

Following that, the dissertation investigates how identity data matching is employed to re-identify applicants within a government migration and asylum agency in The Netherlands. Chapter 5 introduces the concept of re-identification, which involves the ongoing utilization and integration of data from various sources to establish whether multiple sets of identity data pertain to a single individual. This chapter uses insights gathered from interviews with personnel from the agency to investigate the integration of data matching tools for re-identification. The chapter shows that striving to minimize data friction in re-identification through data matching can have unintended consequences and additional burdens for the agency’s personnel.

Lastly, this dissertation examines the evolution of a commercial data matching system employed for identification and security, adopting a sociotechnical approach. Chapter 6 introduces heuristics that are then used to identify moments that emphasize the design contingencies of the data matching system. Through the examination of fieldwork data collected from the company that created the system, the chapter highlights the reciprocal influences between the system’s design and the actors and entities involved. The system experienced adaptive and contingent changes from a generic data matching system to a specialized tool for identification and security because of such influences. In a broader sense, the chapter brings attention to the interrelationships among software suppliers, integrators, and customers, and the circulation and use of knowledge and technology for matching identity data across organizations.

\thispagestyle{plain}