# Nederlandse samenvatting (Summary in Dutch) {.unnumbered .unlisted}

\addcontentsline{toc}{part}{Summary in Dutch}
\chaptermark{Summary in Dutch}

<!-- ::: {lang=nl} -->

\noindent _Het vinden van blinde vlekken: Onderzoek naar identiteitsdatamatching in transnationale gecommercialiseerde veiligheidsinfrastructuur_

\bigskip
<br>

\noindent Deze dissertatie onderzoekt het samenspel tussen datamatching technologieën, identificatiepraktijken en transnationale gecommercialiseerde veiligheidsinfrastructuur, met een specifieke focus op migratie- en grenscontrole. Het onderzoek werd gedreven door een nieuwsgierigheid naar de intersectie tussen datamatching van identiteiten en de zogenaamde "blinde vlekken" waarmee autoriteiten worden geconfronteerd bij het identificeren van individuen, zoals wanneer zij te maken hebben met onvolledige gegevens, aliassen en andere onzekerheden. De dissertatie behandelt de volgende hoofdonderzoeksvraag: "Hoe worden praktijken en technologieën voor het matchen van identiteitsgegevens in migratiemanagement en grenscontrole gevormd door en vormen zij op hun beurt transnationale gecommercialiseerde veiligheidsinfrastructuren?"

De dissertatie begint met een overzicht van de bestaande literatuur over de verbanden tussen datamatchingtechnologie, die in verschillende sectoren wordt gebruikt, en de relaties met de internationalisering, commercialisering, securitisatie en infrastructurering van identificatie. Dit overzicht benadrukt een merkbare kloof in het begrip van hoe datamatching de betekenis van de onderling verbonden gegevens beïnvloedt en de relaties tussen organisaties die het gebruiken vormgeeft. Om deze kloof te dichten, stelt Hoofdstuk 3 een methodologisch kader voor voor het gebruik van datamatching als zowel een onderzoeksonderwerp als een hulpmiddel voor het beantwoorden van specifieke deelvragen met betrekking tot specifieke aspecten van datamatching.

Hoofdstuk 4 benadrukt het belang van datamodellen in informatiesystemen voor het categoriseren van individuen en het tot stand brengen van verbindingen tussen verschillende datamodellen om gegevens te kunnen matchen. De analyse van dit aspect van datamatching wordt mogelijk gemaakt door de introductie van de "Ontology Explorer", die dient als een nieuwe methode voor het onderzoeken van de kennis en aannames die in datamodellen zijn ingebed. Door deze methode toe te passen om nationale en transnationale datainfrastructuren voor bevolkingsbeheer wordt het mogelijk om de denkbeelden van nationale en EU autoriteiten voor bevolkingsbeheer te onderzoeken.  De categorieën van datamodellen komen zo naar voren als een belangrijke manier om inzicht te krijgen in hoe verschillende autoriteiten mensen op verschillende manieren beschouwen en verwezenlijken.

Vervolgens onderzoekt de dissertatie hoe identiteitsdatamatching wordt gebruikt om aanvragers opnieuw te identificeren binnen de processen van een overheidsmigratie- en asielagentschap.Hoofdstuk 5 introduceert het concept van re-identificatie als het herhaaldelijk gebruiken en verbinden van gegevens uit verschillende bronnen om vast te stellen of meerdere sets identiteitsgegevens betrekking hebben op één individu. Het hoofdstuk gebruikt inzichten uit interviews met werknemers van de Immigratie- en Naturalisatiedienst (IND) om de integratie van datamatchingtools voor re-identificatie te onderzoeken. Daaruit blijkt dat hoewel het doel van datamatching vaak is om frictie in re-identificatie te minimaliseren, het gebruik van deze technologie kan leiden tot onvoorziene uitdagingen voor organisaties.

Tot slot onderzoekt deze dissertatie de historische ontwikkeling van een commercieel datamatchingsysteem dat wordt gebruikt voor identificatie- en veiligheidsdoeleinden vanuit een sociotechnisch perspectief. Hoofdstuk 6 introduceert heuristieken die vervolgens worden gebruikt de ontwerpcontingenties van het datamatchingsysteem te identificeren. Op basis van gegevens van interviews en veldwerk verzameld bij het bedrijf dat het systeem heeft gecreëerd, belicht het hoofdstuk de wederzijdse invloeden tussen het ontwerp van het systeem en de betrokken actoren en entiteiten. Het systeem onderging adaptieve en contingente veranderingen van een generiek datamatchingsysteem naar een gespecialiseerd hulpmiddel voor identificatie en beveiliging als gevolg van dergelijke invloeden. Het onderzoek belicht zo de interconnecties tussen softwareleveranciers, integratoren en klanten, evenals de circulatie en het gebruik van kennis en technologie voor het matchen van identiteitsgegevens tussen organisaties.

\thispagestyle{plain}
