# Mapping the theoretical landscape: Unraveling the complexity of matching identity data in transnational security infrastructures {#ch-literature}

\chaptermark{Theoretical framework}

This chapter presents a mapping of theoretical concepts based on literature from four broadly defined areas of research, which will be referred to as (1) “the internationalization of identification”, (2) “the commercialization of identification”, (3) “the securitization of identification”, and (4) “the infrastructuring of identification”. By exploring how identification operates in international, commercial, securitized, and infrastructural contexts, we can develop an understanding of the challenges, implications, and potential consequences associated with data matching practices and technologies. This mapping exercise thus lays the groundwork for generating hypotheses and formulating research questions that relate to the role of matching identity data in transnational commercialized security infrastructures.

The theoretical mapping approach provides an overview of core theories and concepts that provide a framework for the research. While this mapping provides a compass to navigate the subsequent chapters, each empirical chapter will delve into supplementary literature to address the specific research questions pertaining to that chapter's focus. Nonetheless, the theories and concepts introduced in this chapter will play an integral role throughout the dissertation, albeit in varying degrees of explicitness. They provide a theoretical underpinning and serve as a thread that connects the various strands of inquiry throughout the study.

To begin, let us clarify what the theoretical mapping in this chapter covers and how it works alongside the methodological framework from Chapter 3. First, theoretical mapping is used in this dissertation to integrate theories and concepts from multiple research fields and topics more or less directly pertinent to identification and identity data matching. Second, theoretical mapping plays a role in identifying gaps in the existing literature and formulating the research questions, as it allows for raising doubts, questions, and hypotheses informed by literature. Chapter 3 then adds to this theoretical mapping by introducing the methodological framework, a written and visual representation of the specific research, hypotheses, and methods of data collection and analysis that will be used to answer the research questions. Now, let us delve into the first aspect of identification, which is the increasing internationalization, referring to identification practices that extend beyond the confines of the nation-state.

## Internationalization of identification

Identifying people on the move is frequently described as a Janus-faced and multi-sited state-led phenomenon entwined with obligations, rights, and coercive measures that can even occur far from traditional border encounters [e.g., @aboutIdentificationRegistrationPractices2013; @caplanDocumentingIndividualIdentity2001]. The accompanying development of registration and identification systems, such as the creation of civil registers or passports, has, indeed, typically been linked to the state-making of modern nation-states [@breckenridgeRegistrationRecognitionDocumenting2012; @caplanDocumentingIndividualIdentity2001; @torpeyInventionPassportSurveillance2018]. Because identification consequently enables states to track people’s movements and label some as irregular, registration and identification systems and procedures have been argued to facilitate and limit people's freedom of movement across international borders [@broedersDataficationMobilityMigration2016; @squireContestedPoliticsMobility2010; @torpeyInventionPassportSurveillance2018].

A term often referred to for the state’s capacity to identify its citizens is the notion of "legibility" by @scottSeeingStateHow1998. Scott noted how the interaction of premodern states and their population (e.g., for purposes of taxation) went hand in hand with projects of standardization and legibility as attempts to identify its people unambiguously. So, in one example, Scott noted the standardization of diverse cultural naming practices serving specific local purposes in distinct and fixed surnames as “a first and crucial step toward making individual citizens officially legible” (p. 71). Thus, Scott argued that state initiatives like rationalizing surnames enabled states to develop the modern statecraft apparatus, which includes taxpayer lists, conscription lists, censuses, and property deeds, by allowing states to identify the vast majority of their inhabitants unambiguously. Civil registries, identity cards, passports, DNA profiles, and other biometric databases have supplanted fixed surnames. Still, they all serve the same purpose: to make people legible for interactions with states.

Research on the history of identification generally focuses on these state practices of identifying people. For example, @torpeyInventionPassportSurveillance2018, author of the book “The invention of the passport" originally published in 2000, uses Max Weber's aphorism on the legitimacy of the state's use of violence to argue that identification practices gave nation-states a "monopoly of the legitimate means of movement” (p. 2) at the expense of non-state actors like churches and private organizations. Torpey argued that states needed to issue identification documents to maintain the separation between nationals and foreigners and regulate their mobility.

Extending the scope of the discussion beyond the borders of the nation-state, similar registration and identification techniques have been shown to help colonial authorities gain and maintain power, albeit to varying degrees of success [@breckenridgeRegistrationRecognitionDocumenting2012]. The categories of registration and identification systems institutionalized the relationships between the empire’s centre and periphery. However, as @aboutIntroduction2013 points out, registration and identification systems in such imperial and colonial contexts should not be viewed solely as instruments of coercion. What is interesting for our discussion here is how the historical analyses in those edited volumes from @breckenridgeRegistrationRecognitionDocumenting2012 and @aboutIdentificationRegistrationPractices2013 show how identification technologies were brought into a colonial setting, adapted to local conditions and eventually circulated back and forth between the global power centres.

An illustration of such international exchanges of identification technology is provided by @sengooptaImprintRajHow2004, who described how significant advancements in fingerprinting resulted from interactions between colonizers and colonized in the British Empire in India. Interestingly, Sengoopta compares the history of fingerprinting to the spread of curry dishes in English cuisine: "Developed in India but not indigenous, British but not evolved in Britain itself … incorporated into British tradition and then gradually re-transmitted to the world at large, blur[ring] the simplistic distinction we often make between home and Empire" [p. 6, quoted in @coleReviewImprintRaj2005]. While an overview of the history of forensic fingerprinting is beyond the scope of this chapter,[^cole] the main takeaway is that fingerprinting as an identification method has a complicated history, starting with scientists on the European continent, moving through British India's colonial provinces, and finally returning to Victorian England’s Scotland Yard. Therefore, the circulation of identification theories, techniques, and practices reveals the international aspects of identification technology, which can be better understood when considering perspectives beyond the conventional nation-state-based approach.

[^cole]: For a comprehensive overview of the history of fingerprinting in law enforcement, see @coleSuspectIdentitiesHistory2001.

The international nature of identification technologies is especially visible in international policing. International police work goes beyond state practices because of the need to "identify, recog­nize, and track suspects or offenders across an expanding national and eventually international terrain," as the editors of a volume titled "Documenting individual identity: the development of state practices in the modern world" [@caplanDocumentingIndividualIdentity2001, p.9] write. The essays in the book discuss nineteenth-century transnational innovations in identification, such as Bertillon's anthropometric identification system, which became widely used in France and other countries, and the Vucetich fingerprint identification system, which spread from Argentina to other Latin American countries. Based on such examples, the editors note in the book's introduction how policing has been "the source of repeated efforts to rationalize and standardize practices of identification and the systems for the storage and retrieval of the expanding documentation that this generated" (p. 9). International policing, with its emphasis on identifying and tracking suspects across borders, has contributed to the rationalization and standardization of identification practices and technologies.

However, despite the increasing prevalence of identification systems that link identity data from various national and international databases, not much research has been conducted on the operational deployment and utilization of such systems. This scarce research stands in contrast to the amount of real-world examples where such systems have been implemented. Some literature briefly touches upon this point and provides a few examples. For instance, such interconnected database systems are essential for identity verification in the context of Schengen visa applications [e.g., @glouftsiosDesigningDigitalBorders2019] and for detecting potential threats by linking identities across national and international policing and watch listing systems [e.g., @goedePoliticsSecurityLists2016; @zureikGlobalSurveillancePolicing2005]. However, these volumes do not dedicate much attention to other sources of data crucial for the internationalization of identification: the development of international standards for identification [@leeseStandardizingSecurityBusiness2018; @torpeyInventionPassportSurveillance2018]. Further investigation and analysis are thus necessary to understand the operational implementation and implications of the methods, techniques, and tools used to link identity data across databases.

Surprisingly, the essays in Part 1 of @aboutIdentificationRegistrationPractices2013 on "The Central State: Systems, Standards, and Techniques" continue to give priority to state-led standardization projects. This is surprising because current efforts to rationalize and standardize identification systems rely heavily on the work of organizations like the European Commission, the United Nations, Interpol, the International Civil Aviation Organization (ICAO), and the International Organization for Standardization (ISO). For example, the ICAO publishes guidelines for machine-readable passports and visas [@iso/iecIdentificationCardsMachine2008] to ensure “global interoperability”. The American National Standards Institute/National Institute of Standards and Technology Identification Technology Laboratory (ANSI/NIST-ITL) is an example of a government agency that publishes de facto standards for exchanging biometric information such as fingerprints and facial images. In short, rather than a fully coherent system for making people on the move legible, there is more likely a fragmented landscape of systems and data models — and where state vision often needs “fixing” [@leeseFixingStateVision2022] to identify people across international systems.

In this fragmented landscape of systems and data models, data matching emerges as a technological fix to address identification challenges. For example, when individuals move across international borders, their identity data may exist in disparate databases and formats maintained by different authorities and organizations. Data matching technologies can be employed to link these fragmented datasets, enabling a more comprehensive picture of an individual's identity across multiple systems. However, when we connect the internationalization of identification with data matching, it raises several hypotheses, questions, and doubts. How does the use of data matching techniques and technologies facilitate the international exchange of identity data? Are there challenges in harmonizing data matching processes and standards across different authorities and organizations? Does the internationalization of identification require the development of new data matching approaches to account for cultural, linguistic, and contextual variations in identity data? How does the increasing reliance on data matching shape identification outcomes in transnational security contexts? These questions bring attention to the importance of exploring the connections between data matching and the internationalization of identification.

This section has discussed the internationalization of identification, which refers to research into identification practices that extend beyond the boundaries of the nation-state. The need to identify people across borders has brought attention to the importance of identification technology and the efforts to standardize it. The internationalization of identification thus raises research questions regarding the types of knowledge and assumptions about people-on-the-move inscribed in data models of national and transnational security infrastructures. As we will see, it is necessary to develop methods to investigate the interconnections between diverse organizations' and authorities' data models. Furthermore, the diversity of these data models raises the question of how organizations that collect information about people-on-the-move search and match for identity data in their systems and how data are matched and linked across different agencies and organizations. The next section will examine how identification technologies travel across various authorities, states, and organizations and the involvement of different actors, including commercial entities, in their development.

## Commercialization of identification

The edited volume "Identification and registration practices in transnational perspective" [@aboutIdentificationRegistrationPractices2013] is an excellent example of the growing interest in studying identification and registration procedures from an international or transnational perspective in the fields of social and historical research. Furthermore, the editors thus highlight how the volume paves the way for new research into the "increasing takeover of individual identification by corporate bodies for economic purposes" (p. 2). A transnational viewpoint can thus shift the focus away from the nation-state and onto the various other actors involved in identification. Indeed, as noted by @higgsConsumingIdentityConsuming2013 in one of the essays, “the contemporary state’s use of identification technologies, including biometrics, is often dependent upon products created by commercial vendors, who have helped to drive their adoption” (p. 165). Thus, it is interesting to see a growing body of literature acknowledge the importance of non-state and commercial actors in identification processes and technologies [see also @pelizzaIdentificationTranslationArt2021]. This is a topic that has, unfortunately, been explored in a disjointed fashion.

Even though "identification technology is increasingly a commercial product, rather than a creation of the state," as @higgsConsumingIdentityConsuming2013 put it succinctly (p. 165), social and historical research has not followed suit by giving equal weight to these commercial actors in identification. Higgs makes an interesting observation about how historians tend to give the state's identification more weight than, say, commercial enterprises where access to historical records is more closed. Higgs' essay is able to paint a broad picture of the commercial aspect of identification by looking at technological advancements made by private companies in Britain at the beginning of the 18th century. His examples include banks' use of credit and debit cards to identify customers, supermarkets' use of loyalty cards to create consumer profiles and credit reference agencies' determination of a person's creditworthiness. Perhaps unsurprisingly, he concludes his article with the well-documented fact that an increasing number of commercial IT companies actively promote biometric identity systems [see, for example, @amooreBiometricBordersGoverning2006; @olwigBiometricBorderWorld2019; @trauttmansdorffFabricationNecessaryPolicy2022; @zureikGovernanceSecurityTechnology2004].

Higgs and other of the books' essays highlight a gradual shift away from state authorities creating and implementing identification technology to the state purchasing systems created by commercial organizations. Indeed, in the EU context, the political economy of identity management has been shown to consist of only a small network of companies that design, implement, and maintain identity management systems [@lemberg-pedersenPoliticalEconomyEntry2020; @valdiviaNeitherOpaqueTransparent2022]. These small networks have various risks that complicate the relations between standardizing and rationalizing identification as the “involved companies become indispensable, and are granted roles as unrivalled experts in the systems of border control they themselves have designed.” [@lemberg-pedersenPoliticalEconomyEntry2020, p. 71]. @pelizzaIdentificationTranslationArt2021 provides another example of how technology facilitating identification encounters in Greece forges transnational associations with the EU Commission, corporate contractors, and the US security regime through the production of hardware that adheres to US biometric standards, while also leading to vendor lock-in due to the use of proprietary algorithms to create biometric templates. While the significance of commercial identification systems is clear, little is known about the processes involved in their procurement, development, implementation, and deployment.

Beyond that, little is known about the consequences of such international and commercial identification technology on the processes used by states to identify people on the move. A compelling element of @higgsConsumingIdentityConsuming2013's line of reasoning is how he shows not only the impact that commercial innovations have had on the widespread uptake of digital identification technology. Notably, he argues that the uptake and replication of these identification technologies and practices shape how states identify their populace. Therefore, this interdependence highlights the need for research on the evolution and diffusion of identification expertise and technology within and between various public and private institutions.

Linking the commercialization of identification to data matching technology further raises a range of hypotheses, questions, and doubts. Firstly, how does the commercialization of identification impact the development and implementation of data matching technologies used in identification systems? Specifically, how do commercial entities acquire and develop their data matching knowledge and expertise? One possible hypothesis is that commercial data matching systems may play a role in standardizing data matching and identification among different organizations by their underlying mechanisms. What are the effects of deploying these systems on the standardization of identification processes? Moreover, what are the potential risks and challenges associated with the involvement of commercial entities in the design, development, and operation of data matching in identification systems? Could the re-use of data matching technologies by certain vendors or entities become a concern, leading to potential restrictions on competition and innovation in the field? Furthermore, how do companies determine which data matching functionalities to prioritize based on customer needs and industry trends? Further research is needed to explore such relationships between data matching and the commercialization of identification, providing deeper insights into their dynamics, implications, and potential consequences on data matching and identification practices.

In summary, investigating the commercialization of identification provides insights into the proliferation of commercially and internationally available identification systems, which introduces new challenges and complexities. This commercialization is characterized by a shift from state-driven development and implementation of identification technology to state adoption of systems developed by commercial organizations. By delving into the expanded role of commercial actors, we uncover the creation of transnational associations and the potential for vendor lock-in, shedding light on the intricate relationships and power dynamics that underlie the commercialization of identification. Moreover, the commercialization of identification raises considerations regarding the development, implementation, and use of data matching technologies. It prompts us to question how knowledge and technology for matching identity data circulate and travel across organizations. Understanding this circulation would provide insights into the implications of the commercialization of identification. The following section delves into the securitization of identification to explore how security concerns may both influence and be influenced by the design and utilization of identification systems.

## Securitization of identification

The identification of people at the border has become increasingly linked by public and private actors to issues of terrorism and international security, as noted in the preceding chapter's examples from the ongoing EU interoperability project. According to (Critical) Security Studies (CSS) scholars, such construction of identification as a security concern supplants traditional understandings of security and should not be taken for granted. Although security has long been associated with state protection (national security), recent scholarship in CSS has examined the phenomenon's growing influence in new contexts, such as migration, health, and food. As a result, scholars have called into question "the precise definition of what it means to be secure, the causes of insecurity, and who or what the concept of security should apply to" [@peoplesCriticalSecurityStudies2021, p. 2]. In this way, CSS has reformulated the security issue with what is commonly referred to as “broadening” and “deepening” the security-related areas, problems, and actors [@burgessRoutledgeHandbookNew2010; @peoplesCriticalSecurityStudies2021].

On the one hand, security can be characterized as having been "broadened" from its traditional emphasis on more militaristic dimensions to include other areas and threats, such as migration and border security, or health (as the Covid-19 pandemic has shown). On the other hand, what is to be secured (also known as the _referent object_ of security) can be characterized as having been “deepened” to include other actors such as human individuals, cultural/identity groups, multinational corporations, institutions, or even ecosystems. This broadening and deepening of security helps us better understand the shifting dynamics of societal issues like migration and mobility, as well as how different actors are perceived and addressed within the realm of security concerns. Scholars in this field, for example, argue that the securitization of migration in Europe has resulted in policies that criminalize and stigmatize migrants while ignoring the root causes of displacement [e.g., @huysmansEuropeanUnionSecuritization2000]. Similarly, we can see how identification has come to be securitized by looking at the techniques and procedures used for identification.

A crucial question for security scholars is how a specific societal phenomenon, like human migration, health, or the environment, is framed as a threat or security concern. The existence of security threats that need to be dealt with by security authorities and experts may be taken for granted in “traditional” or “essentialist” understandings of security.[^traditional] What if, however, the appearance of security threats operates in reverse? How do societies label specific issues as security threats, and what societal and political consequences does this have? This alternative view is generally how constructivist theories of security share a concern for security as a meaning-making (intersubjective) process in which the interaction and communication between actors construct meanings of the world and shape actors’ identities and power relations [@balzacqConstructivismSecuritizationStudies2009; @peoplesCriticalSecurityStudies2021]. This view becomes particularly relevant in the context of identification and data matching, where the determination of what constitutes a security threat and the practices surrounding it can have significant implications. How are specific issues related to identification and data matching labeled as security threats, and what societal and political consequences does this have?

[^traditional]: "Traditional" or "state-centric" accounts of security, on the other hand, see international relations as occurring only between sovereign nation-states, with states seeking security in a global environment with no universal rules [@peoplesCriticalSecurityStudies2021; @waltRealismSecurity2017]. According to this theory, states' inherent competition with one another would compel them to defend their sovereignty against external threats, in this case, the economic and identity threats posed by migrants.

<!-- In accordance with critical and constructivist perspectives on security, for identification to become a matter of (in)security and securitize, various social, political, and technical work needs to be performed. Security scholars are generally interested in how various discourses, languages, objects, practices, and infrastructure actualize and materialize notions of security.  -->

Constructivist approaches to security can provide insights into the securitization of identification and data matching, by investigating the framing of identification and data matching as security concerns as a social and discursive process, shaped by the interactions and communication between actors.[^constructivist] For instance, “securitization theory” strongly emphasizes how language, discourse, and power all play a part in how security is constructed and the value of critical analysis in challenging the prevailing security narratives and fostering new perspectives on security [ @balzacqThreeFacesSecuritization2005; @buzanSecurityNewFramework1998; @mcdonaldSecuritizationConstructionSecurity2008; @taureckSecuritizationTheorySecuritization2006]. It is important to note that the theory arose out of a concern with the “intellectual and political dangers in simply tacking the word _security_ onto an ever wider range of issues” [@buzanSecurityNewFramework1998, p. 1, emphasis in original]. The core ideas of securitization theory can be attributed to scholars such as Buzan, Waever, and others [@buzanSecurityNewFramework1998; @waeverIdentityMigrationNew1993] who argue that speech acts that treat certain issues as security threats can lead to the expansion of security concerns into other "sectors." That is, how some issues or problems are framed as security threats and elevated to the status of urgent problems requiring extraordinary action.[^desecuritization]

[^desecuritization]: Furthermore, securitization theory enables one to think about the inverse process: how issues might be de-securitized and reintroduced into regular politics.

[^constructivist]: In the fields of security and international relations, some of the earliest sources for the constructivist approach are @adlerSeizingMiddleGround1997, @buzanSecurityNewFramework1998, @huysmansSecurityWhatYou1998, and @wendtAnarchyWhatStates1992.

Securitization theory thus clarifies the implications of simply adding "security" to identification. If identification is being securitized, then the process of securitization entails presenting identification as a pressing security threat. This framing then justifies the use of extraordinary measures to address identification security issues. Chapter 1 provided some examples of how securitization of identification may be seen in the context of the European Union's interoperability framework. In those quotations from policy documents, EU authorities framed the risks of unlinked data as threats to the internal security of the EU as these “unknown unknowns” or “blind spots” are presented as risks that can be exploited by individuals seeking to evade authorities. The construction of identification as a critical security concern supports what could be considered exceptional measures to address these risks through the EU's interoperability framework. For example, the integration of multiple databases and information systems, including those related to visas, asylum, and criminal records that were previously unconnected. Of course, such securitization can also fail if it receives little political or societal backing, as it may be seen as unjustified or out of proportion to the actual security threat.

Securitization theory has been criticized for its focus on the role of the state and its security apparatus in the construction of security issues [@aradauSecurityDemocraticScene2004; @bertrandCanSubalternSecuritize2018; @mcdonaldSecuritizationConstructionSecurity2008; @peoplesCriticalSecurityStudies2021]. Such a viewpoint emphasizes those who can speak, excluding those who have historically and structurally been marginalized. This results in a narrow understanding of security that fails to consider the complexity and diversity of security methods and devices. Therefore, besides the rhetorical structuring of security issues and the performativity of security speech, scholars set about to understand how security is enacted through security devices and in the everyday practices of security professionals [@balzacqSecurityPractices2010; @cote-boucherBorderSecurityPractice2014; @davidshoferTechnologySecurityPractices2017]. Hence, analysis of the technologies, procedures, and protocols used to implement security measures, as well as how these measures are experienced and contested by those subjected to them. Scholars have provided a more comprehensive understanding of how security is enacted and experienced in practice by focusing on the material and embodied dimensions of security [@amicelleQuestioningSecurityDevices2015].

A helpful example of a focus on such security practices is given by Bigo [-@bigoSecuritizationPracticesThree2014], who observed a least three different meanings actors attributed to border control: "solid," something to be defended and connected to sovereignty; "liquid," referring to how borders can be controlled through filtering and identifying populations; and "cloudy," only discernible through the use of digital databases and analytics. In all three of Bigo's examples, the actors' practices and uses of security technology affected the meanings they gave to border control. On the one hand, the practices and technologies can contribute to the securitization of borders and mobility. On the other hand, the technologies created and used are shaped by the meanings attached to borders and border control. Consequently, examining identification and data matching practices and devices makes sense to determine whether, when, and how they might be securitized.

<!-- Additionally, market technologies shape security infrastructures in minor and routine ways, as new technology can reorganize and securitize existing practices. -->

Furthermore, materialist security studies have emerged as another approach which highlights how security is performed through security practices and technology [e.g., @aradauInfrastructure2012; @aradauCriticalMethodsInternational2014; @bellanovaAlgorithmicRegulationSecurity2022; @hoijtinkTechnologyAgencyInternational2019; @waltersDroneStrikesDingpolitik2014], thus prompting us to investigate how identification and data matching technologies actively shape and mediate the construction and enactment of security. Materialist approaches generally focus on objects, such as devices, shaping security practices and outcomes. Materialist security studies seek to account for the development and use of devices in security practices and the agency of these devices. According to @pelizzaIdentificationTranslationArt2021, one compelling feature of materialist security studies is their potential for blurring boundaries between states, private organizations, and commercial entities. Devices like surveillance cameras or biometric scanners are often developed and deployed by various actors, including governments, private security firms, and technology companies. As a result, examining security devices can disentangle different actors' roles and interests in shaping security practices.

Furthermore, devices are not just passive tools in security practices; they also have performativity and can actualize security [e.g., @amicelleQuestioningSecurityDevices2015; @bellanovaControllingSchengenInformation2022; @davidshoferTechnologySecurityPractices2017]. For instance, watch list matching systems used in border security are an example of how identification and data matching technologies shape security practices. Such matching systems effectively process extensive datasets to generate matches and identify potential security threats at borders and airports [see, for example, @glouftsiosEpistemicFusionPassenger2023]. Additionally, biometric authentication systems utilized exemplify devices' performativity in security practices by producing and enacting security classification [e.g., @kloppenburgSecuringIdentitiesBiometric2020]. A materialist perspective on security studies provides a framework for understanding the role of devices in shaping security practices. Focusing on the materiality of security helps illuminate the relationships between actors, devices, and security outcomes.

Similarly, the literature on Science, Technology, and Society (STS) has extensively explored identification in security settings, such as in the context of identifying possible threats in warfare through the lens of sociotechnologies [@follisVisionTransterritoryBorders2017; @suchmanTrackingTargetingSociotechnologies2017]. For instance, consider data matching technologies utilized in security operations to identify potential threats by cross-referencing information from various databases. These algorithmic systems and technological tools play a pivotal role in shaping our understanding of what constitutes a threat and who is considered a legitimate target [@suchmanTrackingTargetingSociotechnologies2017; @suchmanAlgorithmicWarfareReinvention2020]. However, scholars like Lucy Suchman have investigated how such sociotechnologies can lead to unintended consequences, inadvertently creating insecurity for individuals who are wrongly identified or targeted. As such, this perspective urges us to carefully consider the potential risks and wide-ranging implications that arise from data matching and other technological means to identify legitimate targets in security contexts.

The connection between the securitization of identification and data matching thus raises several hypotheses, questions, and doubts that require exploration. Firstly, does the securitization of identification through data matching knowledge target specific groups of people, potentially exacerbating existing inequalities and biases? Secondly, as data matching technology becomes securitized, does the embedded matching knowledge travel between organizations, carrying logic and practices of security with it? Thirdly, do industry trends towards security influence the development and implementation of data matching technology in specific ways? Lastly, how does securitization of data matching technology shape the definition and identification of security threats, and what implication does this have for a broader understanding of security? Further research is necessary to understand these dynamics and the potential consequences for data matching, identification practices and the broader security landscape.

This section has explored the ways in which critical security studies have highlighted the conversion of societal concerns into security issues and the possible consequences of these transformations. Considering the insights from this literature, it becomes crucial to question the justification for categorizing identification as a security issue and the widespread use of data matching techniques. Earlier theories in this field were often limited by a state-centric perspective and a focus on the discourse and speech acts of dominant actors, such as states and security professionals. Recent scholarship has emphasized the materiality and performativity of security practices and devices, as well as their potential to create insecurity for certain groups. This thesis seeks to investigate how security infrastructures shape and are shaped by the specific practices and devices utilized in matching and linking identity data. By examining these processes, we can better understand how identification practices can become securitized and the potential implications for individuals and society. In the following section, we will explore the construction, organization, and interconnection of identification systems, which ultimately create infrastructures that influence data matching and identification procedures.

## Infrastructuring of identification

Literature on infrastructure has long demonstrated how data infrastructures reflect and shape the values, interests, and power relations of the actors involved in their design and operation, which consequently shape practices [e.g., @bowkerSortingThingsOut1999; @edwardsIntroductionAgendaInfrastructure2009; @hansethDevelopingInformationInfrastructure1996; @kitchinCriticalDataStudies2018]. This has particular relevance in border security and migration control, where identifying and tracking individuals across different systems and databases have become crucial components of state surveillance and control. For example, @glouftsiosGoverningBorderSecurity2021 demonstrated how the often-invisible maintenance of large-scale information systems for border security in the EU has an essential role in sustaining the governance of international mobility. Likewise, @pelizzaScriptsAlterityMapping2023, through the notion of “scripts of alterity”, make the point that data infrastructures shape power relations with people and among states. The systems and data infrastructure for identifying people have thus rightly been a frequent concern of studies on border security and migration control [see, for example, @dijstelbloemBordersInfrastructureTechnopolitics2021; @glouftsiosGoverningBorderSecurity2021; @pollozekInfrastructuringEuropeanMigration2019]. This perspective suggests that data matching could be essential in data infrastructure, specifically in linking biometric databases, watch lists, and migration and border management systems. By connecting various organizations, authorities, and their data into more comprehensive data infrastructures, it becomes possible to match and classify individuals for identification purposes effectively.

Yet, defining what constitutes infrastructure often poses a significant challenge due to its multifaceted and dynamic nature [e.g., @edwardsUnderstandingInfrastructureDynamics2007; @larkinPoliticsPoeticsInfrastructure2013; @karastiKnowledgeInfrastructuresPart2016; @monteiroArtefactsInfrastructures2013; @starStepsEcologyInfrastructure1996]. @starStepsEcologyInfrastructure1996, emphasizes infrastructure dimensions such as embeddedness, transparency, reach/scope, learned as part of membership, links with conventions of practice, the embodiment of standards, built on an installed base, and becoming visible on breakdown. Recognizing these complexities helps understand how data matching is intertwined with the infrastructuring of identification, shaping the practices and norms of individuals like border guards and security personnel. The embeddedness of data matching technology within infrastructures may also contribute to transparency and seamless integration of multiple identity databases to enable exchange and interoperability of identity data. Applying @starStepsEcologyInfrastructure1996's dimensions to identification infrastructure would highlight the gradual integration of systems within work practices, evolving over time while adhering to established standards. Such infrastructure operates imperceptibly, remaining invisible until significant events occur.

Similarly, @larkinPoliticsPoeticsInfrastructure2013 captures the ontology of infrastructure as both "things and also the relation between things." His and other relational perspectives emphasize that infrastructure extends beyond its tangible components and encompasses the interdependencies and connections that facilitate its functionality. It underscores the significance of comprehending infrastructure as a network of relationships and dependencies, where material elements intertwine with social and organizational factors. In the context of identification and data matching, this means that infrastructure goes beyond mere databases and systems; it includes the web of relationships that enable effective data exchange and matching processes. Moreover, what may be considered infrastructure for one person or organization might not hold the same significance for others [@starEthnographyInfrastructure1999]. For identification and data matching, different actors may engage with particular infrastructures based on their unique needs, interests, and positions within the broader socio-political landscape. For instance, an immigration agency may prioritize a centralized and secure database infrastructure for accurate identity verification and efficient visa processing, while a law enforcement body may emphasize data matching technologies for cross-referencing identities across multiple databases.

In the context of data matching and identification in infrastructures, it is necessary to consider the impact of the rise of Big Data and its implications for the generation, circulation, and utilization of data [@borgmanBigDataLittle2015; @daltonWhatDoesCritical2014; @kitchinDataRevolutionBig2014]. These developments have sparked interest in new fields like Critical Data Studies (CDS), which seek to uncover the underlying power structures inherent in data practices [@flyverbomDatastructuringOrganizingCurating2018; @iliadisCriticalDataStudies2016; @kitchinCriticalDataStudies2018]. While previous research on infrastructures and social order has taken a relational approach, scholars associated with CDS employ critical frameworks to highlight the power dynamics at play in data processes [@iliadisCriticalDataStudies2016, p. 2]. Furthermore, they emphasize that data are never raw but shaped by choices and constraints [see also, @gitelmanRawDataOxymoron2013]. For example, consider a data matching process used for security purposes. Various datasets, such as passport records, visa applications, and biometric information, are combined to verify identities at border crossings. While the process may seem neutral, the choices made during data matching, like the weight given to specific data points in the matching algorithms, can have significant implications for individuals. CDS, therefore, prompts us to address such questions about the impact of datafication on power relations and the potential risks of data matching in shaping identification outcomes.

The definitions and characteristics discussed bring attention to the dynamic nature of infrastructures as they undergo evolution and adaptation in response to technological advancements, policy changes, and organizational shifts. This raises the question of whether infrastructure can be purposefully designed and built. For instance, @edwardsUnderstandingInfrastructureDynamics2007 emphasizes that infrastructure does not arise from intentional design but grows in phases. This perspective aligns with @hughesNetworksPowerElectrification1983's account of the historical growth of the electrical supply network, where expansion often resulted from addressing critical problems within existing systems. Moreover, as we explore the role of infrastructures in identification systems, it becomes crucial to understand how knowledge and technology for matching identity data circulate and travel across organizations. Edwards et al. emphasize the pivotal phase of constructing gateways in infrastructure development. During this phase, multiple systems compete without a clear winner, and gateways facilitate interoperability, enabling more unified, integrated systems. By exploring how identity data matching technologies traverse organizational boundaries, we can gain insights into the mechanisms contributing to information exchange and interoperability across various organizations.

<!-- In the context of this dissertation, a working definition of data infrastructure, specifically in relation to identification, is adopted. Here, data infrastructure refers to the underlying systems, technologies, regulations, and practices that enable identity data collection, storage, and management. It is essential to note that data infrastructures extend beyond physical or technical components. They encompass sociotechnical arrangements, governance structures, and institutional frameworks that are integral to the functioning of identification systems. Data infrastructures form a complex network of interconnected elements that shape how identity data is created, circulated, managed, and utilized. -->

The connection between the infrastructuring of identification and data matching raises hypotheses, questions, and doubts that warrant further investigation. Firstly, the role of data matching software in facilitating integration and interoperability within identification infrastructures gives rise to hypotheses regarding its impact on the growth and expansion of such infrastructures. For example, do data matching technologies act as crucial components that link diverse databases and systems into broader infrastructures? Accordingly, questions worth considering relate to the implications of data matching for standardization efforts within identification infrastructures. How does data matching interact with existing systems, protocols, regulations, and standards? Does the deployment of data matching software promote or hinder standardization across different identification systems? Additionally, investigating the relationship between infrastructuring and data matching gives rise to hypotheses regarding the often less visible work and technologies involved in matching identity data. How does the embeddedness of data matching technology within infrastructures influence the visibility of identification processes? How do the practices and technologies of data matching contribute to the construction and maintenance of identification infrastructures, and what implications do these have for the overall functioning of identification systems? Exploring these questions and hypotheses can deepen our understanding of the relationships between infrastructuring and data matching in the context of identification systems.

<!-- Understanding such dynamics and challenges of data infrastructures in the context of identification systems is crucial. Collecting, storing, and exchanging identity data rely on complex networks of interconnected systems and organizations. Effective interoperability can be necessary to identify people across infrastructures. Still, it can be hindered by the diverse data formats, protocols, and standards employed by different systems. To examine the interplay between data infrastructures and identification systems, it is necessary to explore the design, implementation, and governance of data infrastructures. Furthermore, understanding infrastructures helps us analyze the implications of identifying individuals across complex data ecosystems. Finally, it enables us to explore how these infrastructures influence and mediate the matching and linking of identity data, thereby shedding light on the shaping and utilization of identity data and the broader implications for transnational security infrastructures. -->

## Research questions

### Main research question

This chapter provided a more precise definition of the research problem and raised doubts, questions, and hypotheses related to data matching in four research areas, (1) the internationalization of identification, (2) the commercialization of identification, (3) the securitization of identification, and (4) the infrastructuring of identification. By analyzing the relevant literature within these areas, we have gained a deeper understanding of the interplay between identification, data matching, and transnational security infrastructures. In addition, the literature review has allowed us to identify key themes within each research area, including the growing use of internationally developed and commercially available identification systems and the increasing securitization of identification processes. These themes have helped to clarify the broader context of identity data matching in the context of transnational commercial security infrastructures.

Through our examination of the internationalization and commercialization of identification, we have identified a gap in research regarding the specific ways in which the spread of commercially and internationally available identification technologies influence identification processes. Similarly, in our exploration of the securitization of identification, we have identified a gap in research regarding how security concerns shape and are shaped by the design and use of identification systems. This securitization can be seen in the growing emphasis on biometric identification in border control and the linking of identity data to identify security threats. Additionally, our examination of the infrastructuring of identification has highlighted a gap in research regarding the implications of identifying people across data infrastructures. It is within this context that the significance of data matching emerges, as a pivotal process in identification and data management that enables the linkage and correlation of identity data across diverse datasets.

The use of data matching technology for identifying individuals across various databases and international borders has raised many questions and uncertainties. When it comes to the internationalization of identification, it brings up concerns about the heterogeneous data models of different authorities, how disjointed identity data can be linked across borders, and how cultural and contextual variations of identity data are taken into account. The commercialization of identification through data matching systems also raises concerns about the involvement of commercial entities, the risks of developing proprietary identification knowledge, and the standardization of identification solutions due to software reuse. The securitization of identification through data matching technology raises concerns about transferring security knowledge between organizations, industry trends in technology development, and defining security threats. Additionally, the infrastructuring of identification and data matching raises questions about the role of data matching in standardization efforts, the invisibility of data matching work in identification processes, and infrastructural growth.

Despite its widespread, further research is required to explore the dynamics and implications of data matching, particularly in the context of emerging technologies, transnational infrastructures, and evolving security concerns. This dissertation aims to contribute to a deeper understanding of the role and influence of data matching technology on the interpretation of data, operational practices, and organizational structures.

Based on these gaps identified in the literature review, we can now formulate the following main research question:

Main research question
: How are practices and technologies for matching identity data in migration management and border control shaping and shaped by transnational commercialized security infrastructures?

This question focuses on the specific contexts of migration management and border control, which concern transnational security infrastructures. The question also highlights the reciprocal relationship between identity data matching practices and technologies and the broader context of transnational security infrastructures. The resulting research question highlights the importance of understanding the interplay between identity data matching, population management, and transnational security infrastructures in migration management and border control. The research question also suggests looking into the implications of these reciprocal relationships for understanding the broader social, economic, and political implications of identity data matching.

### Sub-research question

A range of sub-research questions that delve deeper into the relationship between identification systems and transnational security infrastructures can help to answer our main research question. To this end, the research is structured around three sub-questions that investigate the types of knowledge embedded within data models used by national and transnational security infrastructures (RQ1), the processes and technologies used to search for and match identity data across different organizations (RQ2), and the circulation of knowledge and technology related to matching identity data across organizations (RQ3). In addition, the following sub-questions will address several hypotheses and inquiries regarding the connection between data matching and the internationalization, commercialization, securitization, and infrastructuring of identification that were previously discussed. The three research questions are as follows:

RQ1
: Which types of knowledge and assumptions about people-on-the-move are inscribed in data models of national and transnational security infrastructures? What implications does this have for how organizations can search and match identity data?

RQ2
: How do organizations that collect information about people-on-the-move search and match for identity data in their systems? How is data about people-on-the-move matched and linked across different agencies and organizations?

RQ3
: How does knowledge and technology for matching identity data circulate and travel across organizations?

The research questions posed in this dissertation aim to investigate how knowledge and data about people-on-the-move are matched and linked in transnational security infrastructures. The first research question (RQ1) seeks to uncover the types of knowledge embedded within data models used by different organizations and authorities — what @pelizzaScriptsAlterityMapping2023 have called “scripts of alterity”. Hence, this research question draws inspiration from the technical process of schema matching used in data matching, to focus on data model's design, and the assumptions about people-on-the-move that can be inferred from designs. Uncovering differences can be useful to bring to light division of work in an international setting, and throw light on how infrastructures shape identities. For instance, identifying records that refer to the same person could be challenging without knowledge of the underlying data models of the datasets being matched because the same person may be represented differently across datasets. By focusing on design, we can compare these assumptions to uncover differences in the division of work in an international setting and shed light on how infrastructures shape identities, thereby illuminating the internationalization of identification through the connections between the information about people-on-the-move gathered by various organizations.

The second research question (RQ2) focuses specifically on the ways in which organizations search for and match identity data related to people-on-the-move. This research will explore the processes and technologies used to link and match data across different agencies and organizations, and examine how identity data are collected, stored, and analyzed. By analyzing how data are matched and linked across different organizations, this research can help us better understand the challenges and opportunities associated with managing data related to people-on-the-move. Furthermore, this question can shed light on how emerging and commercially deployed international identification technology shapes state practices. We can gain insight into the invisible aspects of data matching work within infrastructures, and better understand how these technologies shape and maintain identification systems. 

Finally, the third research question (RQ3) explores how knowledge and technology related to matching identity data circulate and travel across organizations. This research will examine the networks of actors and organizations involved in developing and disseminating technologies used for matching identity data and explore how knowledge about such technologies is shared and disseminated among different actors and organizations. Answering this question can aid in our understanding of the broader social and political contexts in which identification technology is developed and used to have long-lasting effects in numerous locations. Through this question, we can investigate how data matching technologies developed in one context can be adopted and adapted in different international settings, possibly affecting identification practices across borders. This research will also spotlight the role of commercial actors in acquiring and disseminating data matching knowledge, which could lead to the concentration of power and expertise in the hands of specific vendors or organizations. Additionally, exploring the circulation of knowledge and technology related to data matching aims to highlight the influence of securitization on identification practices, such as industry trends in security and how they affect software development.
