# Research design and methods {#ch-method}

## Research objectives: Applying and testing the conceptual framework for tracing data matching in transnational security data infrastructures

## Fieldwork site and access

### WCC ELISE — A technology for matching identity data

### Deployments at the IND and EU-VIS

## Methods for data collection

### Traces of data models

### Document analysis

### Interviews

### Events

I collected various relevant publications and participated in events which were organized and attended by a variety of representatives of industry, academia, Member States' authorities, and EU institutions. Table \@ref(tab:fieldwork-events) gives an overview and description of events I participated in, either in person or digitally. The purpose of attending such meetings was to understand how these various actors define and frame the problems and solutions of data quality of personal data in their systems. On one hand, I hypothesized that the presentations and discussions would include useful examples which could help understand the problems actual practitioners are facing. For example, during the Q&A of a panel on the implementation of interoperability at the eu-LISA conference in 2018 a member of the audience asked a question about how they would manage the large amount of false positives which might be triggered when the different databases are connected that contain sometimes old data. The answer given by one of the panellists was that, indeed, a large amount of man-hours will be needed to check all those false positives. This example is revealing of the otherwise background work that is needed to integrate distinct systems.

On the other hand, I hypothesized that the solutions proposed by industry representatives would make evident the kinds of imaginaries related to connecting and using data from different sources. For example, a common trope used to highlight the importance of tools for searching and matching data spread across different databases is based on presumed threats of terrorism. In one presentation, a software company used the real-life example of the Boston bombers who was, prior to the attack, added to police watch lists but with variations in his name and other personal information. The premise of these examples is that having such divergent information across databases makes investigations more difficult for officers, and could be potential blind spots.

During these events I made notes to capture such discussions and problems and solutions of data quality of people's data. In addition, I collected screenshots and other publicly available materials related to these events such as video recordings and handouts. From these notes and pieces of observations and others materials I selected the most relevant to be coded and used in the data analyses.

```{r fieldwork-events, echo=FALSE, ft.align="center"}
path = file.path(TABLES_PATH, "fieldwork-events.csv")
data = read.csv(path, header = TRUE)

block_table(data, header = TRUE, properties = pt)
```

### Other observations

Other observations I use in the analysis are from news articles, press releases, and other articles which I collected to provide additional context and help me understand important moments in the biography of the WCC search and match tool and its deployment at the IND and EU-VIS. Generally, I collected articles which mention the company WCC and/or the of its software in the INDIGO system of the IND or the EU-VIS system. To do these queries I used the LexisNexis database and tool — which aggregates and makes it possible to query all major English and Dutch-speaking newspapers, online business news, and other related publications. For example, I found several articles detailing the progress of the implementation of the INDIGO system that were published in IT business news outlines.

What is not included in the LexisNexis database are some blog posts and announcements by companies publishing information related to the design, development, deployment, and use of the systems. To access such material, I relied on more conventional search engines. For example, I found that a competitor of WCC publishes frequent blog posts on Natural Language Processing such one titled "Understanding Dari and Pashto Names: A Challenge to Intelligence Gathering in Afghanistan" [@rosetteUnderstandingDariPashto2012]. From all such material I selected only the most relevant to be further coded and analyses. This means that, for the analysis, I included only those articles which either directly deal with topics of data quality, data matching, or other relevant discussing surrounding the functioning of the technical systems.

Together these different kinds of materials — news articles, blog posts, press releases — can assist in making a more finished picture of the biography of the software artefacts for searching and matching identity data.

## Techniques of data analysis
