# Supplement to Chapter 5

## Interview protocol {#appendix-protocol}

[comment]: <> "LTeX: language=nl"

* Kun je me kort in je eigen woorden uitleggen wat je rol binnen de IND is, wat je taken zijn/waren en hoe je de applicaties voor het zoeken naar personen hebt gebruikt?
* Welke informatie heb je nodig voordat je een zoekopdracht kan doen?
  +	Zijn er bepaalde situaties waar je vooraf al weet of een zoekopdracht niet goed gaat lukken?
  + Wat zijn de minimum velden denk je die nodig zijn voor een goede/exacte match?
  + Helpt de applicatie je bij het formuleren van een zoekopdracht? Hoe zou dit volgens jou kunnen gebeuren?
* Kun je me uitleggen welke velden je invult voor het zoeken naar personen.
  + Zijn er volgens jou bepaalde velden die betere resultaten opleveren?
  + In de zoekvelden kun je soms ook gebruik maken van speciale symbolen zoals een sterretje (* wildcards) waardoor je de zoekopdracht flexibeler kan maken. Maak je hiervan gebruik? Indien ja, voor welke velden wel en welke niet?
  + Ben je er bewust van dat er ook bepaalde functionaliteiten in de zoekapplicatie zitten die bijvoorbeeld makkelijker moeten maken om te zoeken met verschillende alfabetten of verschillen in hoe namen fonetisch klinken enz.
* Kun je me uitleggen hoe je de juiste persoon vindt in de lijst van resultaten?
  + Is het altijd duidelijk waarom bepaalde resultaten in de lijst staan?
  + Als er zeer vergelijkbare resultaten zijn in de lijst, hoe identificeer je dan de juiste persoon?
  + Zijn er soms te veel resultaten in de lijst volgens jou?
* In de lijst van resultaten staat er normaal steeds een match score, weet jij hoe die berekend wordt?
  + Zijn de match scores die worden toegekend aan de resultaten nuttig volgens jou?
  + Hoe zouden deze match scores verbeterd kunnen worden?
* Vind je de lijst van resultaten betrouwbaar? Hoe kun je dit volgens jou zien?
  + Heb je soms duplicaten in de resultatenlijst gezien? Hoe zie je dit? En waarom denk je dat dit soms voorkomt?
  + Ik heb vernomen dat er soms ook een memo aan personen gehangen wordt voor extra informatie, kun je me uitleggen hoe dit juist gebruikt wordt?
* Ik heb begrepen dat sommige personen in de database relaties hebben met andere personen. Wat soort relaties zijn dit? En heeft dit een invloed op hoe je zoekopdrachten doet?
* Op welke databases worden de zoekopdrachten uitgevoerd volgens jou? Enkel de system binnen de IND, of ook van andere partners?
  + Zijn er verschillen in hoe personen in deze andere system staan?
* Hoe heb jij gebruik leren maken van de applicaties en zoekfunctionaliteiten. Was dit via ervaringsdeskundigen, collega’s, of?

### Inkomende poststukken vragen

* Kun je me uitleggen hoe je het verschil vindt of je moet zoeken op een al bestaande klant of een nieuwe klant zal moeten aanmaken.
  + Help de applicatie je hiermee? Hoe zou dit volgens jou beter kunnen?

### Deduplicatie vragen

* Volgens welke criteria worden er volgens jou duplicaten gevonden?
* Waarom zijn er volgens jou duplicaten in de IND database en waarom is het belangrijk om deze te vinden en corrigeren?
* Hoe gebeurd de rapportage van duplicaten? Wat zijn de stappen die je onderneemt nadat je deze resultaten hebt gekregen?
  + Hoe ga je dubbele klanten samenvoegen? Treden er soms moeilijkheden op?
* Ik heb gehoord dat de historische waarden belangrijk zijn voor IND. In hoeverre is dit ook zo voor de deduplicatie?

[comment]: <> "LTeX: language=en"

## Search strategies {#appendix-protocol}

```{r tab.cap="Examples of search strategies", tab.id = "strategies", tab.cap.style = "Table Caption", echo=FALSE, ft.align="center"}
path = file.path(DATA_PATH, "search_strategies.csv")
data = read.csv(path, header = TRUE)

data$Code = substring(data$Name, first=34)

block_table(data[,c("Code", "Comment")], header = TRUE, properties = pt)
```
