# Supplement to Chapter 6

## Interview questions

* Can you briefly explain to me your position/function at WCC?
* Identity matching:
  + What are some challenges of matching identity data across different organizations, according to you?
  + What about matching identity data across different locales, for example, between EU Member States or national and international organizations or institutions?
  + What is the role of WCC solutions in making identity data interoperable?
* From your experience, are some kinds or categories of data more important for matching identity data?
* Can you tell me something about these needs of the customers. Do they always know what they want in how the data matching should work?
* What are some of the most important features of WCC solutions that you highlight to the customer? And vice versa, what features may the customer see as important when you talk to them?
* Generification of the software:
  + How can software such as identity matching work across different contexts/domains be made possible? For example, how can it be made to work in employment and security?
  + In the case of security, are there differences and challenges to doing such things as identity matching in domains such as policing vs. migration or travel?
* Tensions of customizable/generic software for the customer.
  + At the IND, I found that some of the challenges for users to work with the search tools are due to the way ELISE is deployed as a very generic service in the SOA, with few adaptations for the specific context of the IND.
* I have sometimes heard the WCC solution described as “vendor-neutral.” What is your view on this issue?
  + Do you know of cases when proprietary formats or algorithms were an issue?
  + How can software such as ELISE work with different data formats?
