# Theoretical mapping and conceptual framework

## The varying meanings of theory

Although the terms conceptual framework, theoretical framework, and theoretical mapping are closely related (and sometimes used interchangeably[@merriamQualitativeResearchGuide2016]), it can be analytically useful to differentiate between these terms[@anfaraTheoreticalFrameworksQualitative2015; @imendaThereConceptualDifference2014; @ravitchReasonRigorHow2017]. What these concepts do have in common is a concern for how researchers’ use of (social) theory interacts with empirical data collection, analysis, and interpretation. Not surprising for such a loaded term as “theory,” there has been much discussion on the use of theory in STS [@harawayGameCatCradle1994; @latourRecallingANT1999; @lawSTSMethod2017; @pickeringDecenteringSociologySynthetic2005; @roosthScienceTechnologyStudies2008; @singletonFeminismSociologyScientific1996] and, more generally, social science research [@abendMeaningTheory2008; @blumerWhatWrongSocial1954; @freeseFormalTheorizing1980; @mertonSociologicalTheory1945; @parsonsRoleTheorySocial1938; @turnerIntroductionNewAgenda2008]. For this reason, it will be instructive to review some of the debates that have occurred and consider their implications for the theoretical mapping we are constructing.

The term “theory” has many connotations in and of itself. One of the most thorough attempts to map these theoretical meanings was made by @abendMeaningTheory2008, who created a typology with at least eight varieties. According to her typology, theory can mean any of the following: the well-worn definition as a “logically interconnected sets of propositions from which empirical uniformities can be derived” [@mertonSociologicalTheoriesMiddle1968, p. 39], the work of _theorists_ of classical and contemporary theory, the (causal) “explanation” of empirical social phenomena, and the perspectives/lenses/views/… which frame and shape how and what researchers look at. The importance of theory for our purposes in developing the theoretical mapping will be more closely related to the latter meanings of directing the analysis, as will become clear in the remainder of this section.

@abendMeaningTheory2008 notes how terms like “theory” and “theoretical” are terms that “can _simultaneously_ do descriptive and evaluative work” (p. 192, emphasis in original). In other words, these terms are often used to describe research and imply an opinion of a work. Similarly, the terms theory and theoretical can imply a value judgement of whether scientists can have a detached and value-neutral perspective [compare with @mertonNormativeStructureScience1973’s norms of science]. Contrarily, theory can be political, as shown by works connected to, for instance, feminist theory or postcolonial theory, which have a significant normative component. Indeed, as we shall see in the mapping, theories and concepts from literature such as Critical Security Studies (CSS) have such a significant normative component; in CSS’s case, a rejection of the narrow focus of conventional approaches to security.

Theory, in capital letters, thus stands for another distinguishing characteristic: how formalized, well-established, and generally accepted theoretical frameworks are in their respective fields. According to @ravitchReasonRigorHow2017, theory can be part of “off the shelf” or “informal” theoretical or conceptual frameworks (p.5). In off-the-shelf frameworks, researchers may employ established or emerging theoretical approaches from their fields. For instance, a survey by @sovacoolOrderingTheoriesTypologies2017 highlighted social scientists' theories and concepts to understand sociotechnical diffusion and change, such as "Sociotechnical Transitions" (also known as the "Multilevel Perspective"), "Social Practice Theory", "Domestication Theory", "Large Technical Systems", "Social Construction of Technology", and  "Sociotechnical Imaginaries". These perspectives and frameworks emphasize and question different aspects of the relationships between technology and various forms of social life and order. An investigation will thus typically be positioned and guided in a rather strict sense when using an off-the-shelf framework.

Alternatively, theoretical concepts can be integrated into an “informal” framework, according to @ravitchReasonRigorHow2017. However, it should be noted that the distinction between off-the-shelf and informal are also not clear-cut. As @sovacoolOrderingTheoriesTypologies2017 and their respondents remark, many previous perspectives already integrate concepts from different fields. Nevertheless, if one is alert to potential incompatibilities between theories, as @sovacoolOrderingTheoriesTypologies2017 argues, “integrative theory” can be advantageous as “a way to minimize bias and arrogance, best fit a particular research topic or question, tighten concepts through critical thinking, and aid researchers in a quest for meta-theoretical triangulation” (p. 742). In this sense, the theoretical mapping will adopt a more informal or integrative approach as the first building block in the structure of this dissertation to outline how theory and concepts frame and shape the investigation.

## Theory-dependence and reality amplifiers

Another crucial view of theory comes from the history and philosophy of science, more precisely, Kuhn's view of theories as components of scientific “paradigms” [@kuhnStructureScientificRevolutions2012], which are opposing and frequently incompatible ways of explaining the world. In Kuhn’s view, a paradigm defines what constitutes “normal science” as sets of generally accepted theories, concepts, rationales, and ideas among scientific communities. Thus, it is possible that findings may or may not be accepted by the scientific community, depending on whether they align with the established paradigm or require a paradigm shift. Additionally, this perspective on science asserts that scientists cannot rely on _raw observations_ because their observations are shaped by the paradigms scientists work within (also known as _theory dependence of observation_).[^sismondo] In this sense, theory-dependence constitutes a problem because it implies that researchers may unintentionally assume the result that their observations are supposed to support when gathering evidence to support that result. The main lesson to draw from this is the importance of being aware of how theories align with the prevailing paradigm and recognizing that how the dissertation's theories and concepts are put into practice can significantly impact the findings obtained.

[^sismondo]: For a historical context of these ideas within STS, see @sismondoChapterKuhnianRevolution2010.

Approaches closely related to actor-network theory and material-semiotic analysis offer additional valuable insights into how theories are constructed and enacted in practice [e.g., @callonTranslationsProblematicNetworks1983; @latourRecallingANT1999; @lawANTComplexityNaming1999]. In Law's words: “it is important not to start out assuming whatever we wish to explain” [@lawNotesTheoryActornetwork1992, p. 380]. Essentially, we should not assume, at the outset of an investigation, that a theoretical distinction between, for instance, micro- and macro-sociological phenomena exists and can be used to explain power dynamics. Instead, theories like actor-network theory argue that we should explain how something comes to be considered as large as an outcome rather than making such a priori distinctions between small and large [@latourReassemblingSocialIntroduction2005]. This is a crucial point to keep in mind because theories and concepts in the mapping may assume the existence of elusive concepts like a “biometric border regime” or even a “state” [see also, @mitchellLimitsStateStatist1991].

Furthermore, in light of recent debates surrounding the performativity of language in shaping social reality, it is crucial to keep in mind that theories and concepts go beyond merely describing some aspect of the world [see, for example, @aradauPerformingMethodsPractice2017 and @lawMethodMessSocial2004]. As @lawMethodMessSocial2004 puts it: “Method always works not simply by detecting but also by amplifying a reality” (p. 116). Instead, theories and methods actively shape how we understand and interact with the world around us.  Consequently, “framing” the dissertation within a set of theories and concepts like the securitization of identity or travelling software contributes to producing those realities. Thus, a critical engagement with the theories and concepts utilized in the dissertation is essential for a comprehensive understanding of the research and its broader implications.

The conceptual framework and theoretical mapping in this dissertation are in close agreement with such STS perspectives that emphasize the interdependence of theory and methodology. STS generally recognizes that the development of theory is an ongoing process that emerges from empirical observations and shapes how we address research questions. In this sense, the dissertation’s use of particular terminology and concepts will reflect underlying theoretical assumptions and epistemological commitments informing the research. As such, the theories and concepts employed in the dissertation have actual effects on how the research is conducted, how the data are interpreted, and, ultimately, on the implications of the findings.

Lastly, the dissertation is multidisciplinary in nature, employing theory and concepts in a more modest manner. It is worth remembering that theories and theoretical concepts can also be “communication devices,” or “abstractions or generalizations that can help us to convey our ideas to policy makers (and other nonacademic groups), to students, between different academic communities, or between STS scholars studying different objects” [@wyattHomeRangeWhat2007, p. 622]. As a result, the theoretical mapping aids in communicating the research to other academics and nonacademic communities. The following sections will develop the theoretical mapping of concepts used in the dissertation. After that, Chapter 3 will introduce a conceptual framework that will methodologically direct the investigation of a specific empirical case.
